apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmp-aggregation-bs
  namespace: dtag-dev
  labels:
    app: bmp-aggregation-bs
    version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bmp-aggregation-bs
      version: latest
  template:
    metadata:
      name: bmp-aggregation-bs
      labels:
        app: bmp-aggregation-bs
        version: latest
    spec:
      containers:
      - name: bmp-aggregation-bs
        image: 10.0.5.16:5000/bm/aggregation-business-service:latest
        args: ["--spring.profiles.active=pannet"]
        imagePullPolicy: Always
      imagePullSecrets:
      - name: onap
        resources:
          requests:
            cpu: 200m
            memory: 0.5Gi
        ports:
        - containerPort: 9005
