apiVersion: v1
kind: ReplicationController
metadata:
  namespace: dev-env
  name: aggregation-service
  labels:
    app: aggregation-service
    version: latest
spec:
  replicas: 1
  selector:
    app: aggregation-service
    version: latest
  template:
    metadata:
      name: aggregation-service
      labels:
        app: aggregation-service
        version: latest
    spec:
      containers:
      - name: aggregation-service
        image: mohammadaszadali/aggregation-business-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: aggregation-service
  namespace: dev-env
  labels:
    app: aggregation-service
    version: latets
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32765
    Protocol: Tcp
  selector:
    app: aggregation-service
    version: latest
  
