adduser: /bsi/5gslices/v1/addContact
coreCreateCustomer: /bsi/CustomerManagement/v1/single
coreCustomer:
    url: http://10.0.5.10
datg:
    email: /bsi/5gslices/v1/getByEmailId
dtagCreateCustomer: /bsi/5gslices/v1/newcustomer
dtagCustomer:
    url: http://10.0.5.10
dtagGetCustomer: /bsi/5gslices/v1/getCustomers
keycloak:
    auth-server-url: http://10.0.5.10:8287/auth
    bearer-only: true
    credentials:
        secret: 5c41361c-eaca-4519-915f-7086bf8ee7ad
    mail:
        url: http://10.0.5.35:30955/emailservice/v1/mailTempPassword
    public-client: true
    realm: UserManagement
    resource: UserManagement
    securityConstraints:
    - null
    -   authRoles:
        - user
        securityCollections:
        -   name: user
            patterns:
            - /user/*
    userRepre:
        url: http://10.0.5.35:30955/keycloak/updateUserName
keyclockurl: http://10.0.5.35:30955/keycloak/create
logging:
    level:
        org:
            keycloak: TRACE
resetpwdkeyclockurl: http://10.0.5.35:30955/keycloak/reset
server:
    port: 9005
spring:
    data:
        mongodb:
            database: BMP_SKUID_1
            host: 10.0.5.36
            port: 27017
userlogin: /bsi/5gslices/v1/SignIn
